apiVersion: v1
kind: Service
metadata:
  name: jguard
  namespace: jguard
  labels:
    app: jguard
spec:
  type: ClusterIP
  selector:
    app: jguard
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP